#!/usr/bin/env python3
"""Build source-data manifest for PF-ERI manuscript display items."""

from __future__ import annotations

import csv
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = PROJECT_ROOT / "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_source_data_package"

CLAIM_BOUNDARY = (
    "CzechLynx human reviewability/evidential admissibility and review-routing "
    "utility only; no automated identity assignment, Bobcat identity accuracy, "
    "retrieval mAP, MRR, top-k identity improvement, or universal cross-domain "
    "risk-control guarantee."
)

DISPLAY_ITEMS = [
    {
        "display_item": "Figure 1",
        "description": "Conceptual evidence-admission chain after descriptor retrieval.",
        "generated_outputs": [
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue1/figure1_pair_level_evidence_admission_chain.svg",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue1/figure1_pair_level_evidence_admission_chain.pdf",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue1/figure1_pair_level_evidence_admission_chain.png",
        ],
        "source_artifacts": [
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue1/story_hardening_issue1_figure_audit.json",
            "docs/modeling-validation/2026-07-09_manuscript_evidence_chain_outline.md",
        ],
        "generation_command": "Generated by scripts/build_story_hardening_issue1_figure.py",
        "claim_boundary": "Conceptual workflow only; not a model-performance claim.",
    },
    {
        "display_item": "Figure 2",
        "description": "Reviewability model comparison and active-control increments.",
        "generated_outputs": [
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/figure2_model_comparison.svg",
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/figure2_model_comparison.pdf",
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/figure2_model_comparison.png",
        ],
        "source_artifacts": [
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue3/issue3_core_incremental_model_comparison.csv",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue3/issue3_core_incremental_model_evidence_audit.json",
        ],
        "generation_command": "python3 scripts/build_manuscript_figures_tables.py",
        "claim_boundary": "Reviewability model comparison only; mixed descriptor-specific increments block universal superiority claims.",
    },
    {
        "display_item": "Figure 3",
        "description": "Quality and descriptor-similarity sensitivity analyses.",
        "generated_outputs": [
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/figure3_quality_similarity_sensitivity.svg",
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/figure3_quality_similarity_sensitivity.pdf",
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/figure3_quality_similarity_sensitivity.png",
        ],
        "source_artifacts": [
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue4/issue4_quality_matched_sensitivity.csv",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue4/issue4_high_quality_subset.csv",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue4/issue4_high_similarity_subset.csv",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue4/issue4_rank_similarity_stratified_sensitivity.csv",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue4/issue4_quality_similarity_sensitivity_audit.json",
        ],
        "generation_command": "python3 scripts/build_manuscript_figures_tables.py",
        "claim_boundary": "Sensitivity evidence only; non-estimable and negative boundary strata remain boundaries.",
    },
    {
        "display_item": "Figure 4",
        "description": "Fixed-budget review utility and pre-inference evidence hygiene.",
        "generated_outputs": [
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/figure4_review_budget_utility.svg",
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/figure4_review_budget_utility.pdf",
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/figure4_review_budget_utility.png",
        ],
        "source_artifacts": [
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue5/issue5_fixed_budget_review_utility.csv",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue5/issue5_fixed_budget_policy_delta.csv",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue5/issue5_review_budget_value_audit.json",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue6/issue6_pre_inference_evidence_hygiene_summary.csv",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue6/issue6_pre_inference_evidence_hygiene_audit.json",
        ],
        "generation_command": "python3 scripts/build_manuscript_figures_tables.py",
        "claim_boundary": "Review-routing utility only; same-ID retention is a queue-composition audit.",
    },
    {
        "display_item": "Table 1",
        "description": "Dataset and validation contract.",
        "generated_outputs": [
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/table1_dataset_validation_contract.csv",
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/table1_dataset_validation_contract.md",
        ],
        "source_artifacts": [
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue3/issue3_core_incremental_model_comparison.csv",
            "archive/pferi_v1/outputs/modeling-validation/blind-reliability-packet/agreement-analysis/blind_reliability_agreement_summary.csv",
            "archive/pferi_v1/outputs/modeling-validation/blind-reliability-packet/agreement-analysis-reviewer2/blind_reliability_agreement_summary.csv",
            "archive/pferi_v1/outputs/modeling-validation/bobcat-wild-urban-transfer-stress/bobcat_transfer_stress_summary.csv",
        ],
        "generation_command": "python3 scripts/build_manuscript_figures_tables.py",
        "claim_boundary": "Validation contract table; Bobcat remains unlabeled transfer-stress.",
    },
    {
        "display_item": "Table 2",
        "description": "Pooled and descriptor-specific model comparison.",
        "generated_outputs": [
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/table2_model_comparison.csv",
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/table2_model_comparison.md",
        ],
        "source_artifacts": [
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue3/issue3_core_incremental_model_comparison.csv",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue3/issue3_core_incremental_model_evidence_audit.json",
        ],
        "generation_command": "python3 scripts/build_manuscript_figures_tables.py",
        "claim_boundary": "Reviewability model comparison only; not identity or retrieval performance.",
    },
    {
        "display_item": "Table 3",
        "description": "Review routing and pre-inference evidence hygiene.",
        "generated_outputs": [
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/table3_review_routing_evidence_hygiene.csv",
            "archive/pferi_v1/outputs/manuscript/2026-07-10_pferi_figures_tables/table3_review_routing_evidence_hygiene.md",
        ],
        "source_artifacts": [
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue5/issue5_fixed_budget_review_utility.csv",
            "archive/pferi_v1/outputs/modeling-validation/story-hardening-issue6/issue6_pre_inference_evidence_hygiene_summary.csv",
        ],
        "generation_command": "python3 scripts/build_manuscript_figures_tables.py",
        "claim_boundary": "Workflow and evidence hygiene table; not identity accuracy.",
    },
]


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def csv_row_count(path: Path) -> int | None:
    if path.suffix.lower() != ".csv":
        return None
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.reader(handle)
        rows = sum(1 for _ in reader)
    return max(rows - 1, 0)


def file_meta(path_str: str) -> dict[str, object]:
    path = PROJECT_ROOT / path_str
    exists = path.exists()
    meta: dict[str, object] = {"path": path_str, "exists": exists}
    if exists:
        meta.update(
            {
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
                "csv_rows": csv_row_count(path),
            }
        )
    return meta


def markdown_table(rows: list[dict[str, object]], columns: list[str]) -> str:
    lines = ["| " + " | ".join(columns) + " |", "| " + " | ".join(["---"] * len(columns)) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(str(row.get(col, "")).replace("\n", " ") for col in columns) + " |")
    return "\n".join(lines) + "\n"


def write_csv(path: Path, rows: list[dict[str, object]], columns: list[str]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    display_rows: list[dict[str, object]] = []
    file_rows: list[dict[str, object]] = []
    missing: list[str] = []

    for item in DISPLAY_ITEMS:
        display_rows.append(
            {
                "display_item": item["display_item"],
                "description": item["description"],
                "generated_outputs": "; ".join(item["generated_outputs"]),
                "source_artifacts": "; ".join(item["source_artifacts"]),
                "generation_command": item["generation_command"],
                "claim_boundary": item["claim_boundary"],
            }
        )
        for role in ("generated_outputs", "source_artifacts"):
            for path_str in item[role]:
                meta = file_meta(path_str)
                meta["display_item"] = item["display_item"]
                meta["role"] = role
                file_rows.append(meta)
                if not meta["exists"]:
                    missing.append(path_str)

    display_cols = ["display_item", "description", "generated_outputs", "source_artifacts", "generation_command", "claim_boundary"]
    file_cols = ["display_item", "role", "path", "exists", "bytes", "sha256", "csv_rows"]
    write_csv(OUT_DIR / "display_item_source_map.csv", display_rows, display_cols)
    write_csv(OUT_DIR / "source_file_manifest.csv", file_rows, file_cols)

    (OUT_DIR / "display_item_source_map.md").write_text(markdown_table(display_rows, display_cols), encoding="utf-8")
    (OUT_DIR / "source_file_manifest.md").write_text(markdown_table(file_rows, file_cols), encoding="utf-8")

    audit = {
        "status": "PASS" if not missing else "FAIL_MISSING_FILES",
        "built_at_utc": datetime.now(timezone.utc).isoformat(),
        "claim_boundary": CLAIM_BOUNDARY,
        "display_item_count": len(DISPLAY_ITEMS),
        "file_record_count": len(file_rows),
        "missing_files": missing,
        "regeneration_commands": [
            "python3 scripts/build_story_hardening_issue1_figure.py",
            "python3 scripts/build_manuscript_figures_tables.py",
            "python3 scripts/build_manuscript_source_data_package.py",
        ],
    }
    (OUT_DIR / "source_data_package_audit.json").write_text(json.dumps(audit, indent=2, sort_keys=True), encoding="utf-8")

    readme = f"""# PF-ERI Manuscript Source Data Package

Date: 2026-07-10

This package maps each manuscript display item to generated files, source
artifacts, generation commands, and claim boundaries. It is a manifest package;
it does not duplicate the underlying CSV/JSON artifacts.

## Claim Boundary

{CLAIM_BOUNDARY}

## Files

- `display_item_source_map.csv` and `.md`: display-item to source-artifact map.
- `source_file_manifest.csv` and `.md`: file-level manifest with size, SHA-256,
  and CSV row counts where applicable.
- `source_data_package_audit.json`: build audit and regeneration commands.

## Regeneration Commands

```bash
python3 scripts/build_story_hardening_issue1_figure.py
python3 scripts/build_manuscript_figures_tables.py
python3 scripts/build_manuscript_source_data_package.py
```
"""
    (OUT_DIR / "README.md").write_text(readme, encoding="utf-8")

    print(f"Built source-data package in {OUT_DIR.relative_to(PROJECT_ROOT)}")
    print(f"Status: {audit['status']}")
    if missing:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
